### ISSUE TITLE
Unable to start frontend container

### ISSUE THREAD

**Issue by VenuNarukulla** [flurdy/docker-compose-machine-swarm-cloud-example#1]
Hi,

This is great work that you put all together. I am experimenting with these stack of technologies.

I am not able to create frontend container . Below is the message. Please can you advise?
I have maven configured but not Ivy. Is it a problem?

<pre>
Recreating dockerexample_maven_1...
Recreating dockerexample_database_1...
Recreating dockerexample_service_1...
Recreating dockerexample_frontend_1...
Cannot start container 34b717cf72e2ede61ee012038d7e6787e5f7f1874e2acc34337587a569c15752: [8] System error: exec: "\"/opt/app/target/universal/stage/bin/frontend\"": stat "/opt/app/target/universal/stage/bin/frontend": no such file or directory
</pre>

docker-compose Logs

<pre>Attaching to dockerexample_frontend_1, dockerexample_service_1, dockerexample_database_1, dockerexample_maven_1, fa6f9a8464_dockerexample_frontend_1
service_1  | 18:15:40.102 [main] INFO  c.flurdy.example.server.Application - Starting Pizzeria Service
service_1  | [INFO] [07/05/2015 18:15:41.668] [Pizzeria-system-akka.actor.default-dispatcher-2] [akka://Pizzeria-system/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8880
service_1  | [INFO] [07/05/2015 18:15:41.671] [Pizzeria-system-akka.actor.default-dispatcher-4] [akka://Pizzeria-system/deadLetters] Message [akka.io.Tcp$Bound] from Actor[akka://Pizzeria-system/user/IO-HTTP/listener-0#271592105] to Actor[akka://Pizzeria-system/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
frontend_1 | exec: "\"/opt/app/target/universal/stage/bin/frontend\"": stat "/opt/app/target/universal/stage/bin/frontend": no such file or directory
database_1 | LOG:  database system was interrupted; last known up at 2015-07-05 18:12:46 UTC
database_1 | LOG:  database system was not properly shut down; automatic recovery in progress
database_1 | LOG:  redo starts at 0/16A8178
database_1 | LOG:  record with zero length at 0/16BD7D0
frontend_1 | exec: "\"/opt/app/target/universal/stage/bin/frontend\"": stat "/opt/app/target/universal/stage/bin/frontend": no such file or directory
database_1 | LOG:  redo done at 0/16BD7A0
database_1 | LOG:  last completed transaction was at log time 2015-07-05 18:12:48.089683+00
database_1 | LOG:  MultiXact member wraparound protections are now enabled
database_1 | LOG:  autovacuum launcher started
database_1 | LOG:  database system is ready to accept connections
</pre>

docker-compose ps:

<pre>
dockerexample_database_1   /docker-entrypoint.sh postgres   Up        5432/tcp                
dockerexample_frontend_1   "/opt/app/target/universal ...   Exit -1                           
dockerexample_maven_1      /bin/bash                        Exit 0                            
dockerexample_service_1    /opt/app/src/main/resource ...   Up        0.0.0.0:49920->8880/tcp 
</pre>

**Comment by flurdy** [comment]
Yup, reproduced. Will fix :)

**Comment by flurdy** [comment]
Fixed with latest commit which wraps entrypoint properly
